#!/bin/python
#*********************************************************************
#The MIT License (MIT)
#
#Copyright (c) 2016 Christopher Asakawa, Mathew O'Brien, Nicholas McHale, Corey Aing
#
#Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files
# (the "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# permit persons to whom the Software is furnished to do so, subject 
# to the following conditions:
#
#The above copyright notice and this permission notice shall be 
# included in all copies or substantial portions of the Software.
#
#THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
# OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND 
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT 
# WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING 
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR 
# OTHER DEALINGS IN THE SOFTWARE.
#*******************************************************************
import os
import requests
import binascii
#******************************************
# This function will return to the caller the 
# 	Requested number of random bytes
#	that have been generated by the SushiRNG 
#******************************************
def rand(numBytes = 1):
	headers={'number-bytes-requested': 1000}
	randBytes = ''

	if numBytes < 1:
		return randBytes
	else:
		bytesToFetch = numBytes
		while bytesToFetch > 1000:

			r = requests.get('http://127.0.0.1:5000/getBytes', headers=headers)
			if r.status == 200:
				randBytes = randBytes + r.text
			else:
				return randBytes

			bytesToFetch = bytesToFetch -1000

		headers['number-bytes-requested'] = bytesToFetch
		r = requests.get('http://127.0.0.1:5000/getBytes', headers=headers)
		if r.status == 200:
			randBytes = randBytes + r.text
			
		return randBytes